language: python
python:
  - 3.5
  - 3.4
  - 2.7
sudo: false
addons:
  apt:
    packages:
    - libev4
    - libev-dev
notifications:
  email:
    - tbarbugli@gmail.com
    - thierryschellenbach@gmail.com
cache: pip
env:
  - CASSANDRA_DRIVER="3.7.1"
  - CASSANDRA_DRIVER="3.6.0"
  - CASSANDRA_DRIVER="3.5.0"
  - CASSANDRA_DRIVER="3.4.1"
  - CASSANDRA_DRIVER="3.3.0"
  - CASSANDRA_DRIVER="3.2.2"
  - CASSANDRA_DRIVER="3.1.1"
  - CASSANDRA_DRIVER="3.0.0"
  - CASSANDRA_DRIVER="2.7.2"

matrix:
  fast_finish: true
  exclude:
    - python: 3.5
      env: CASSANDRA_DRIVER="3.3.0"
    - python: 3.5
      env: CASSANDRA_DRIVER="3.2.2"
    - python: 3.5
      env: CASSANDRA_DRIVER="3.1.1"
    - python: 3.5
      env: CASSANDRA_DRIVER="3.0.0"
    - python: 3.5
      env: CASSANDRA_DRIVER="2.7.2"
    - python: 3.4
      env: CASSANDRA_DRIVER="3.3.0"

services:
  - redis
  - cassandra
before_install:
  - git clone https://github.com/tbarbugli/stream_framework_example.git pinterest_example
before_script:
  - echo 'DROP KEYSPACE test_stream_framework;' | /usr/local/cassandra/bin/cqlsh;
install:
  - pip install --upgrade pip
  - pip install cassandra-driver==$CASSANDRA_DRIVER
  - pip install -e .[redis,cassandra]
  - pip freeze
  - pip install cassandra-driver==$CASSANDRA_DRIVER
script:
  - CQLENG_ALLOW_SCHEMA_MANAGEMENT="yes" py.test -l --tb=short stream_framework/tests
